function  MIMM_set_path( )
[STR, ~, ~] = fileparts(mfilename('fullpath'));
addpath(fullfile(STR,'Dictionary'),...
        fullfile(STR,'Dictionary_Generation'),...
        fullfile(STR,'Example_Data'),...
        fullfile(STR,'Matching_Pursuit'));
end